#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Prevent commits to main
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ]; then
  echo "Direct commits to main are prohibited. Please use a feature branch."
  exit 1
fi

bun run lint
bun run typecheck
bun run test
bun run coverage
bun run verify-complexity
